# Generated by Django 5.0.2 on 2026-04-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="reminder_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
