# Generated by Django 5.0.2 on 2026-04-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_add_reminder_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="notes/audio/"),
        ),
    ]
