# Generated by Django 5.0.2 on 2026-04-04 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_add_order_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["-pinned", "-order_id", "-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="note",
            name="notes_user_id_429168_idx",
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["user", "-pinned", "-order_id"], name="notes_user_id_8a3538_idx"
            ),
        ),
    ]
