# Generated by Django 5.0.2 on 2026-03-16 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_todo_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(fields=["user", "deleted"], name="todos_user_id_4c2949_idx"),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["user", "-pinned", "-created_at"], name="todos_user_id_f4796b_idx"
            ),
        ),
    ]
