# Generated by Django 5.0.2 on 2026-03-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0005_alter_todo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="notes/thumbs/"),
        ),
    ]
