# Generated by Django 5.0.2 on 2026-03-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_verification_token_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="verification_token",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
