# Generated by Django 5.0.2 on 2026-03-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_bio_alter_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_token",
            field=models.CharField(blank=True, db_index=True, default="", max_length=100),
        ),
    ]
