# Generated by Django 5.0.2 on 2026-04-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_add_user_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="device_fingerprint",
            field=models.CharField(db_index=True, default="", max_length=255),
        ),
    ]
